### ISSUE TITLE
Doesn't build in Ubuntu 14.04

### ISSUE THREAD

**Issue by ghost** [james4k/go-bgfx#3]
I know that it's mentioned it may only work on Mac right now, but I'd really like to play around with this and I don't have a Mac.

This is the error I'm getting after running $ go get github.com/james4k/go-bgfx

`# github.com/james4k/go-bgfx
/usr/bin/ld: $WORK/github.com/james4k/go-bgfx/_obj/bgfx.cpp.o: undefined reference to symbol 'XFree'
//usr/lib/x86_64-linux-gnu/libX11.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status`

Any help to build this in ubuntu would be appreciated.

**Comment by james4k** [comment]
There will be a number of issues getting it to build outside of Mac, but it wants to link against X11 for GL context creation. See https://github.com/james4k/go-bgfx/blob/master/bridge.go for the current linker arguments.

Eventually, would like to move context creation out of bgfx, or at least be optional.

I haven't worked on this in some time due to other priorities, so can't say when work will resume, but future projects will depend on it.

**Comment by james4k** [comment]
A good interim solution would be to keep your rendering API in Go fairly high level, and do all of your bgfx rendering calls in C/C++.
